# Generated by Django 5.2 on 2026-03-19 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bbox', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='tasks.image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='labels.label')),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
    ]
