# Generated by Django 5.2 on 2026-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='bbox',
            field=models.TextField(max_length=30),
        ),
    ]
